# Generated by Django 4.1.6 on 2023-02-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={"permissions": (("can_mark_returned", "Set book as returned"),)},
        ),
    ]
